# Generated by Django 2.1 on 2018-09-04 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='song_title',
            field=models.CharField(default='ringer', max_length=500),
            preserve_default=False,
        ),
    ]
