# Generated by Django 2.2.4 on 2019-08-08 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_song_song_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='artists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FILE_TYPE', models.CharField(max_length=10)),
                ('song_type', models.CharField(max_length=100)),
                ('song_title', models.CharField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='album',
            name='album_logo',
            field=models.FileField(upload_to=''),
        ),
    ]
