# Generated by Django 2.2.4 on 2019-08-08 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20190808_2224'),
    ]

    operations = [
        migrations.DeleteModel(
            name='artists',
        ),
    ]
